# Generated by Django 4.1 on 2022-08-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('documento', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField()),
                ('fecha_entrega', models.DateField()),
                ('entregado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.IntegerField()),
                ('costo', models.FloatField()),
                ('precio', models.FloatField()),
                ('rubro', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('documento', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
